"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0irie*#p=^a46@c&b_d*h!i9qxy7d8g*&@ba2#%8#!(^zlqxk&'

# SECURITY WARNING: don't run with debug turned on in production!
# Set to False in production to prevent sensitive information leakage
DEBUG = True

ALLOWED_HOSTS = []

# Security Settings
# These settings enhance the security of the application by adding browser-side protections
# and ensuring secure communication

# CSRF Protection
# Ensures CSRF cookies are only sent over HTTPS in production
# Set to True in production to prevent CSRF attacks
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Session Security
# Ensures session cookies are only sent over HTTPS in production
# Set to True in production to prevent session hijacking
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Browser Security Headers
# Enable browser's XSS filtering to help prevent cross-site scripting attacks
SECURE_BROWSER_XSS_FILTER = True

# Prevent browsers from MIME-sniffing a response away from the declared content-type
# This helps prevent attacks based on MIME-type confusion
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking Protection
# Prevents the site from being framed, protecting against clickjacking attacks
# DENY: The page cannot be displayed in a frame, regardless of the site attempting to do so
X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'csp',  # Django Content Security Policy
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy middleware
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
# This setting specifies the custom user model to be used for authentication
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Content Security Policy (CSP) Settings
# CSP helps prevent XSS attacks by specifying which domains can be used to load content
# These settings define a restrictive policy that only allows content from trusted sources

from csp.constants import NONCE

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        # Allow content only from the same origin by default
        'default-src': ["'self'"],
        
        # Allow scripts from self with nonce support for inline scripts
        'script-src': ["'self'", NONCE],
        
        # Allow styles from self and inline styles (needed for some functionality)
        'style-src': ["'self'", "'unsafe-inline'"],
        
        # Allow images from self and data URIs (for base64 encoded images)
        'img-src': ["'self'", "data:"],
        
        # Allow fonts from self only
        'font-src': ["'self'"],
        
        # Restrict AJAX, WebSocket connections to same origin
        'connect-src': ["'self'"],
        
        # Prevent the site from being framed (clickjacking protection)
        'frame-ancestors': ["'none'"],
    }
}
